-- ========================================================
-- DayBySpring Bookstore v2 - Supabase PostgreSQL 17 DDL
-- Target: Supabase 'sm-book-store' (yoqxnuejqyszeqwckdtl)
-- Schema: public
-- ========================================================

DROP TABLE IF EXISTS purchase_approval_items CASCADE;
DROP TABLE IF EXISTS purchase_approvals CASCADE;
DROP TABLE IF EXISTS refunds CASCADE;
DROP TABLE IF EXISTS deliveries CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS loan CASCADE;
DROP TABLE IF EXISTS book CASCADE;
DROP TABLE IF EXISTS member CASCADE;

-- 1. member (회원)
CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    membership_type VARCHAR(20) DEFAULT 'REGULAR',
    join_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_member_email ON member (email);
CREATE INDEX idx_member_name ON member (name);
CREATE INDEX idx_member_role ON member (role);

-- 2. book (도서)
CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    isbn VARCHAR(17) NOT NULL UNIQUE,
    price NUMERIC(10, 2) NOT NULL,
    price_currency VARCHAR(3) DEFAULT 'KRW',
    available BOOLEAN NOT NULL DEFAULT TRUE,
    cover_image_url VARCHAR(500),
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITH TIME ZONE,
    deleted_date TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_book_isbn ON book (isbn);
CREATE INDEX idx_book_title ON book (title);
CREATE INDEX idx_book_author ON book (author);

-- 3. loan (대여)
CREATE TABLE loan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES member(id) ON DELETE RESTRICT,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE RESTRICT,
    loan_date TIMESTAMP WITH TIME ZONE NOT NULL,
    due_date TIMESTAMP WITH TIME ZONE NOT NULL,
    return_date TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    overdue_fee NUMERIC(10, 2) DEFAULT 0.00,
    overdue_fee_currency VARCHAR(3) DEFAULT 'KRW',
    extension_count INT NOT NULL DEFAULT 0,
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_loan_member_id ON loan (member_id);
CREATE INDEX idx_loan_book_id ON loan (book_id);
CREATE INDEX idx_loan_date ON loan (loan_date);
CREATE INDEX idx_loan_status ON loan (status);

-- 4. orders (주문)
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES member(id) ON DELETE RESTRICT,
    total_amount NUMERIC(10, 2) NOT NULL,
    total_currency VARCHAR(3) DEFAULT 'KRW',
    discount_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    discount_currency VARCHAR(3) DEFAULT 'KRW',
    points_used INT NOT NULL DEFAULT 0,
    points_earned INT NOT NULL DEFAULT 0,
    coupon_code VARCHAR(50),
    order_date TIMESTAMP WITH TIME ZONE NOT NULL,
    confirmed_date TIMESTAMP WITH TIME ZONE,
    shipped_date TIMESTAMP WITH TIME ZONE,
    delivered_date TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    cancelled_date TIMESTAMP WITH TIME ZONE,
    cancellation_reason VARCHAR(255),
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_order_member_id ON orders (member_id);
CREATE INDEX idx_order_date ON orders (order_date);
CREATE INDEX idx_order_status ON orders (status);
CREATE INDEX idx_order_created_date ON orders (created_date);

-- 5. order_item (주문 항목)
CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE RESTRICT,
    quantity INT NOT NULL DEFAULT 1,
    price NUMERIC(10, 2) NOT NULL,
    price_currency VARCHAR(3) DEFAULT 'KRW'
);

CREATE INDEX idx_order_item_order_id ON order_item (order_id);
CREATE INDEX idx_order_item_book_id ON order_item (book_id);

-- 6. payments (결제)
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,
    method VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    amount NUMERIC(10, 2) NOT NULL,
    amount_currency VARCHAR(3) DEFAULT 'KRW',
    payment_date TIMESTAMP WITH TIME ZONE,
    transaction_id VARCHAR(100) UNIQUE,
    payment_key VARCHAR(200),
    pg_provider VARCHAR(50),
    receipt_url VARCHAR(500),
    card_company VARCHAR(50),
    card_number VARCHAR(30),
    installment_months INT DEFAULT 0,
    failure_reason VARCHAR(255),
    failed_date TIMESTAMP WITH TIME ZONE,
    cancelled_date TIMESTAMP WITH TIME ZONE,
    refunded_amount NUMERIC(10, 2) DEFAULT 0.00,
    refunded_currency VARCHAR(3) DEFAULT 'KRW',
    refunded_date TIMESTAMP WITH TIME ZONE,
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_payment_order_id ON payments (order_id);
CREATE INDEX idx_payment_transaction_id ON payments (transaction_id);
CREATE INDEX idx_payment_status ON payments (status);

-- 7. deliveries (배송)
CREATE TABLE deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,
    recipient_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,
    zip_code VARCHAR(10),
    address VARCHAR(255) NOT NULL,
    address_detail VARCHAR(255),
    delivery_memo VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'PREPARING',
    tracking_number VARCHAR(100),
    courier_company VARCHAR(50),
    shipped_date TIMESTAMP WITH TIME ZONE,
    delivered_date TIMESTAMP WITH TIME ZONE,
    estimated_delivery_date TIMESTAMP WITH TIME ZONE,
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_delivery_order_id ON deliveries (order_id);
CREATE INDEX idx_delivery_status ON deliveries (status);

-- 8. refunds (환불)
CREATE TABLE refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
    amount NUMERIC(10, 2) NOT NULL,
    amount_currency VARCHAR(3) DEFAULT 'KRW',
    reason VARCHAR(1000) NOT NULL,
    requested_by VARCHAR(100),
    request_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_date TIMESTAMP WITH TIME ZONE,
    rejected_date TIMESTAMP WITH TIME ZONE,
    completed_date TIMESTAMP WITH TIME ZONE,
    approved_by VARCHAR(100),
    rejected_by VARCHAR(100),
    rejection_reason VARCHAR(500),
    bank_name VARCHAR(50),
    account_number VARCHAR(50),
    account_holder VARCHAR(50),
    refund_transaction_id VARCHAR(100),
    processing_memo VARCHAR(500),
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_refund_order_id ON refunds (order_id);
CREATE INDEX idx_refund_status ON refunds (status);

-- 9. purchase_approvals (도서 구매/품의 결재)
CREATE TABLE purchase_approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id BIGINT NOT NULL REFERENCES member(id) ON DELETE RESTRICT,
    approver_id BIGINT REFERENCES member(id) ON DELETE RESTRICT,
    title VARCHAR(200) NOT NULL,
    purpose TEXT,
    department VARCHAR(100),
    total_amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    rejection_reason VARCHAR(500),
    order_id BIGINT,
    submitted_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_date TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_approval_applicant ON purchase_approvals (applicant_id);
CREATE INDEX idx_approval_status ON purchase_approvals (status);
CREATE INDEX idx_approval_submitted_date ON purchase_approvals (submitted_date);

-- 10. purchase_approval_items (품의 도서 목록)
CREATE TABLE purchase_approval_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_id BIGINT NOT NULL REFERENCES purchase_approvals(id) ON DELETE CASCADE,
    book_id BIGINT,
    book_title VARCHAR(200) NOT NULL,
    book_author VARCHAR(100),
    isbn VARCHAR(30),
    quantity INT NOT NULL,
    estimated_price NUMERIC(10, 2) NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL
);

CREATE INDEX idx_approval_item_approval ON purchase_approval_items (approval_id);
